### ISSUE TITLE
Current futures contracts not displaying correct data

### ISSUE THREAD

**Issue by hcgaron** [jeog/TOSDataBridge#12]
Thanks for the excellent work on this library.

I  noticed tonight that overnight futures data doesn't seem to report the correct price (sometimes returning all zeros, sometimes returning wrong data).  Maybe this isn't a bug and it's a consequence of the data stream, but wanted to share my note.

Tonight calling /ES data returned LAST:  2921.75.  When querying /CL I'm getting LAST: 73.56.  These are returning data but not sure why they're so out of date.

FWIW, today is the first time I've run the software, so I shouldn't have a cache or anything stored locally.

EDIT: I'm running this overnight from the USA.

EDIT2: I’ve tested this during normal trading hours and I’m getting the same result. Even if I explicitly write the contract month and year in (full symbol) the data isn’t current. Equities and ETFs update as expected. I noticed that when entering the symbol `/ES` it is returned in the results as `X_ES`, and `/CL` is returned as `X_CL`. Perhaps it’s a character issue?

**Comment by jeog** [comment]
Thanks for pointing this out. It appears this an issue w/ TOS, not TOSDB (getting stale futures data through the excel DDE formula as well). Not sure when this behavior changed because it worked fine in the past. Equities and Options still seem to work fine.

You can always send them an email asking why DDE no longer appears to be working w/ futures contracts.

**Comment by hcgaron** [comment]
>Thanks for pointing this out. It appears this an issue w/ TOS, not TOSDB (getting stale futures data through the excel DDE formula as well). Not sure when this behavior changed because it worked fine in the past. Equities and Options still seem to work fine. ...

@jeog thanks; I emailed TD and I’ll let you know if I get a reply. Not sure their general support staff will be too helpful on such an issue but worth a shot.

**Comment by hcgaron** [comment]
I received a helpful email from TD that solved the issue. Here is their reply:

```
Thanks for the email. You should be able to export Futures data. 

If you are trying to export to an old list, you may need to manually update symbols since there was a change:

A quick cheat sheet for all Futures products:

/ES:XCME
/NQ:XCME
/YM:XCBT
/RTY:XCME
/NKD:XCME
/EMD:XCME
/VX:XCBF
/BTC:XCME
/XBT:XCBF
/CL:XNYM
/QM:XNYM
/NG:XNYM
/QG:XNYM
/RB:XNYM
/HO:XNYM
/BZ:XNYM
/GC:XCEC
/MGC:XCEC
/SI:XCEC
/SIL:XCEC
/HG:XCEC
/PL:XNYM
/PA:XNYM
/ZB:XCBT
/ZN:XCBT
/ZF:XCBT
/ZT:XCBT
/UB:XCBT
/TN:XCBT
/GE:XCME
/ZQ:XCBT
/GLB:XCME
/6A:XCME
/M6A:XCME
/6B:XCME
/M6B:XCME
/6C:XCME
/6E:XCME
/E7:XCME
/M6E:XCME
/6J:XCME
/J7:XCME
/6M:XCME
/6N:XCME
/6S:XCME
/ZC:XCBT
/XC:XCBT
/ZS:XCBT
/XK:XCBT
/ZW:XCBT
/XW:XCBT
/KE:XCBT
/ZM:XCBT
/ZL:XCBT
/ZO:XCBT
/HE:XCME
/GF:XCME
/LE:XCME
/LBS:XCME
/FNG:IFUS
/MME:IFUS
/DX:IFUS
/YG:IFUS
/YI:IFUS
/CT:IFUS
/CC:IFUS
/KC:IFUS
/SB:IFUS
/OJ:IFUS

```

**Comment by jeog** [comment]
I've update the docs /w the new symbols. Thanks again.
