### ISSUE TITLE
Level-2 Data

### ISSUE THREAD

**Issue by jshridha** [jeog/TOSDataBridge#14]
Is there any way to get a stream of the level-2 data from ToS? I don't see it in the documentation but I'm unsure if I'm missing it or if that feature just hasn't been built out.

**Comment by jeog** [comment]
I don't believe TOS exports L2 data via DDE. If you can come up with a way to get it into a thinkscript study you could export it via [CUSTOM topics](https://github.com/jeog/TOSDataBridge/blob/master/README_DETAILS.md#custom-topics).
