### ISSUE TITLE
Fail to run test codes for Java 

### ISSUE THREAD

**Issue by xyang5987** [jeog/TOSDataBridge#15]
I tried 3 tests. Except the last one, others are not success. You may know what the problem is. 

1) TimeAndSales runs failed on both dlls. The error message for tos-databridge-0.9-x64.dll is "Failed to Connect to TOS(CONN_ENGINE)".  The error message for _tos-databridge-x64.dll is "TOSDataBridge Exception: library not loaded", where I tried to change the dll file name in order to avoid some name problems.  

2)  TOSDataBridgeTest has a link problem to native lab with _tos-databridge-x64.dll

directory: \data\finance\lib\tosdatabridge\x64, name: _tos-databridge-x64
TOSDataBridge.init(..) failed to load library: java.lang.UnsatisfiedLinkError: Error looking up function 'TOSDB_Connect': The specified procedure could not be found.

java.lang.UnsatisfiedLinkError: Error looking up function 'TOSDB_Connect': The specified procedure could not be found.

	at com.sun.jna.Function.<init>(Function.java:245)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:566)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:542)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:528)
	at com.sun.jna.Library$Handler.invoke(Library.java:228)
	at com.sun.proxy.$Proxy0.TOSDB_Connect(Unknown Source)
	at io.github.jeog.tosdatabridge.TOSDataBridge.connect(TOSDataBridge.java:164)
EXCEPTION: LibraryNotLoaded
io.github.jeog.tosdatabridge.TOSDataBridge$LibraryNotLoaded: library not loaded
	at io.github.jeog.tosdatabridge.TOSDataBridge.init(TOSDataBridge.java:141)
	at com.norvar.testcenter.trials.TOSDataBridgeTest.main(TOSDataBridgeTest.java:73)
io.github.jeog.tosdatabridge.TOSDataBridge$LibraryNotLoaded: library not loaded
	at io.github.jeog.tosdatabridge.TOSDataBridge.init(TOSDataBridge.java:148)
	at com.norvar.testcenter.trials.TOSDataBridgeTest.main(TOSDataBridgeTest.java:73)

*** DONE (FAILURE) ***

3. TOSDataBridgeTest can run with tos-databridge-0.9-x64.dll a few steps, but got an error. The message is as follows.

directory: \data\finance\lib\tosdatabridge\x64, name: tos-databridge-0.9-x64
NOT CONNECTED
block limit: 10
double block limit
block limit: 20
block count: 0

CREATE BLOCK 1...
Block: b4a90404-9e1c-48bd-b7eb-6ec8a585da11
using datetime: false
timeout: 2000
block size: 100000
Successfully created block: b4a90404-9e1c-48bd-b7eb-6ec8a585da11
Add items: [/ZN, /ES]
Block: b4a90404-9e1c-48bd-b7eb-6ec8a585da11
item(pre-cache): /ZN
item(pre-cache): /ES

Item pre-cache looks good: [/ZN, /ES]
Successfully caught exception from adding NULL_TOPIC: io.github.jeog.tosdatabridge.TOSDataBridge$InvalidItemOrTopic: 'NULL_TOPIC' is not a valid Topic
Successfully caught exception from adding null topic: java.lang.NullPointerException: null topic enum
Successfully caught exception from adding empty item string: io.github.jeog.tosdatabridge.TOSDataBridge$InvalidItemOrTopic: invalid item string length: 0
Successfully caught exception from adding too large item string: io.github.jeog.tosdatabridge.TOSDataBridge$InvalidItemOrTopic: invalid item string length: 256
Add Topics: [LASTX, LAST_SIZE, LAST, CUSTOM1]
EXCEPTION: CLibException
io.github.jeog.tosdatabridge.TOSDataBridge$CLibException: CLib call [TOSDB_AddTopic] failed; ERROR_DECREMENT_BASE(-2)
io.github.jeog.tosdatabridge.TOSDataBridge$CLibException: CLib call [TOSDB_AddTopic] failed; ERROR_DECREMENT_BASE(-2)

	at io.github.jeog.tosdatabridge.DataBlock.addTopic(DataBlock.java:329)
	at com.norvar.testcenter.trials.TOSDataBridgeTest.testBlock1(TOSDataBridgeTest.java:181)
	at com.norvar.testcenter.trials.TOSDataBridgeTest.main(TOSDataBridgeTest.java:78)
*** DONE (FAILURE) ***

Thanks

Xuefeng

**Comment by xyang5987** [comment]
I should post the log messages.

service-log:

DATE / TIME                         Process ID  Thread ID   Log TAG             Severity    Description

Sun Feb 03 02:00:58 2019 [843411]   9764        11052       STARTUP             LOW         lpCmdLn: 
Sun Feb 03 02:00:58 2019 [843913]   9764        11052       STARTUP             LOW         argc: 0 custom_session: -1 admin_pos: 0 no_service_pos: 0
Sun Feb 03 02:00:58 2019 [844911]   9764        1596        ADMIN               LOW         successfully registered control handler
Sun Feb 03 02:00:58 2019 [844911]   9764        1596        STATE               LOW         SERVICE_START_PENDING 
Sun Feb 03 02:00:58 2019 [845411]   9764        1596        STARTUP             LOW         start tos-databridge-engine.exe (AS A SERVICE)
Sun Feb 03 02:00:58 2019 [845909]   9764        1596        SPAWN               LOW         (4) set session id: 2 (this may may fail during (6) 'CreateProcessAsUser')
Sun Feb 03 02:00:58 2019 [870178]   9764        1596        STATE               LOW         SERVICE_RUNNING 

engine-log:
DATE / TIME                         Process ID  Thread ID   Log TAG             Severity    Description

Sun Feb 03 02:00:58 2019 [886080]   13804       6352        STARTUP             LOW         is_service == true
Sun Feb 03 02:00:58 2019 [887080]   13804       6352        STARTUP             LOW         lpCmdLn args: --spawned --service 
Sun Feb 03 02:00:58 2019 [893067]   13804       6352        STARTUP             LOW         entering RunMainCommLoop
Sun Feb 03 02:01:36 2019 [75899]    13804       6352        STREAM              HIGH        error creating new topic stream, ERROR# -22
Sun Feb 03 02:01:36 2019 [75899]    13804       6352        STREAM-OP           HIGH        Error (-22) in AddStream (LASTX,/ES,2000)
Sun Feb 03 02:01:38 2019 [483031]   13804       6352        STREAM              HIGH        error creating new topic stream, ERROR# -22
Sun Feb 03 02:01:38 2019 [483031]   13804       6352        STREAM-OP           HIGH        Error (-22) in AddStream (LASTX,/ZN,2000)
Sun Feb 03 02:10:37 2019 [709166]   13804       6352        STREAM              HIGH        error creating new topic stream, ERROR# -22
Sun Feb 03 02:10:37 2019 [709166]   13804       6352        STREAM-OP           HIGH        Error (-22) in AddStream (LASTX,/ES,2000)
Sun Feb 03 02:10:39 2019 [771665]   13804       6352        STREAM              HIGH        error creating new topic stream, ERROR# -22
Sun Feb 03 02:10:43 2019 [620914]   13804       6352        STREAM-OP           HIGH        Error (-22) in AddStream (LASTX,/ZN,2000)
Sun Feb 03 02:37:09 2019 [882864]   13804       6352        STREAM              HIGH        error creating new topic stream, ERROR# -22
Sun Feb 03 02:37:09 2019 [883332]   13804       6352        STREAM-OP           HIGH        Error (-22) in AddStream (LASTX,/ES,2000)
Sun Feb 03 02:37:11 2019 [942299]   13804       6352        STREAM              HIGH        error creating new topic stream, ERROR# -22
Sun Feb 03 02:37:11 2019 [942299]   13804       6352        STREAM-OP           HIGH        Error (-22) in AddStream (LASTX,/ZN,2000)
Sun Feb 03 02:38:38 2019 [625576]   13804       6352        STREAM              HIGH        error creating new topic stream, ERROR# -22
Sun Feb 03 02:38:38 2019 [625576]   13804       6352        STREAM-OP           HIGH        Error (-22) in AddStream (LAST,/ES,2000)
Sun Feb 03 02:38:40 2019 [651143]   13804       6352        STREAM              HIGH        error creating new topic stream, ERROR# -22
Sun Feb 03 02:38:44 2019 [486744]   13804       6352        STREAM-OP           HIGH        Error (-22) in AddStream (LAST,/ZN,2000)

**Comment by jeog** [comment]
Code should only be linked against/initialize 'tos-databridge-0.9-x64.dll'; 

'_tos-databridge-0.9-x64.dll' is a back-end library shared by the different modules and just needs to be in a location the other modules can find(best to keep it in same directory as other binaries). Don't  try to link/initialize with this lib.

The 'Failed to Connect to TOS(CONN_ENGINE)' indicates the library was loaded and was able to communicate w/ the engine/service but the engine couldn't communicate with TOS. **Make sure TOS is running and there isn't a mismatch in privileges or the session.** [See the Troubleshooting Readme.](https://github.com/jeog/TOSDataBridge/blob/master/README_TROUBLESHOOTING.md#connection-problems) 

The errors you see in the third test and in the logs have to do with the fact that [TDMA recently changed symbols for futures contracts](https://github.com/jeog/TOSDataBridge#new-symbols-for-futures-contracts) and I forgot to update the tests. I just pushed commit 6a5a08c to fix this. 

Let me know how this test works with the updated symbols.

jon

**Comment by xyang5987** [comment]
Thanks for the reply.

I am using a Dell laptop to run everything. Do I still have "Service/Engine" issue? 

I'll start to check your new commit.

Thanks,

Xuefeng

**Comment by xyang5987** [comment]
Here are the new test results:

directory: \data\finance\lib\tosdatabridge\x64, name: tos-databridge-0.9-x64
NOT CONNECTED
block limit: 10
double block limit
block limit: 20
block count: 0

CREATE BLOCK 1...
Block: 6cbd4d28-c73e-45a1-a451-44fafacd3a10
using datetime: false
timeout: 2000
block size: 100000
Successfully created block: 6cbd4d28-c73e-45a1-a451-44fafacd3a10
Add items: [/ES:XCME, /ZN:XCBT]
Block: 6cbd4d28-c73e-45a1-a451-44fafacd3a10
item(pre-cache): /ES:XCME
item(pre-cache): /ZN:XCBT

Item pre-cache looks good: [/ES:XCME, /ZN:XCBT]
Successfully caught exception from adding NULL_TOPIC: io.github.jeog.tosdatabridge.TOSDataBridge$InvalidItemOrTopic: 'NULL_TOPIC' is not a valid Topic
Successfully caught exception from adding null topic: java.lang.NullPointerException: null topic enum
Successfully caught exception from adding empty item string: io.github.jeog.tosdatabridge.TOSDataBridge$InvalidItemOrTopic: invalid item string length: 0
Successfully caught exception from adding too large item string: io.github.jeog.tosdatabridge.TOSDataBridge$InvalidItemOrTopic: invalid item string length: 256
Add Topics: [LASTX, LAST_SIZE, LAST, CUSTOM1]
EXCEPTION: CLibException
io.github.jeog.tosdatabridge.TOSDataBridge$CLibException: CLib call [TOSDB_AddTopic] failed; ERROR_DECREMENT_BASE(-2)
io.github.jeog.tosdatabridge.TOSDataBridge$CLibException: CLib call [TOSDB_AddTopic] failed; ERROR_DECREMENT_BASE(-2)

	at io.github.jeog.tosdatabridge.DataBlock.addTopic(DataBlock.java:329)
	at com.norvar.testcenter.trials.TOSDataBridgeTest.testBlock1(TOSDataBridgeTest.java:182)
	at com.norvar.testcenter.trials.TOSDataBridgeTest.main(TOSDataBridgeTest.java:78)
*** DONE (FAILURE) ***

engine-log
DATE / TIME                         Process ID  Thread ID   Log TAG             Severity    Description

Sun Feb 03 20:03:32 2019 [815997]   12632       13148       STARTUP             LOW         is_service == true
Sun Feb 03 20:03:32 2019 [816497]   12632       13148       STARTUP             LOW         lpCmdLn args: --spawned --service 
Sun Feb 03 20:03:32 2019 [821525]   12632       13148       STARTUP             LOW         entering RunMainCommLoop
Sun Feb 03 20:05:57 2019 [406036]   12632       13148       STREAM              HIGH        error creating new topic stream, ERROR# -22
Sun Feb 03 20:05:57 2019 [406490]   12632       13148       STREAM-OP           HIGH        Error (-22) in AddStream (LASTX,/ES:XCME,2000)
Sun Feb 03 20:06:04 2019 [898739]   12632       13148       STREAM              HIGH        error creating new topic stream, ERROR# -22
Sun Feb 03 20:06:04 2019 [898739]   12632       13148       STREAM-OP           HIGH        Error (-22) in AddStream (LASTX,/ZN:XCBT,2000)
Sun Feb 03 20:08:21 2019 [246704]   12632       13148       STREAM              HIGH        error creating new topic stream, ERROR# -22
Sun Feb 03 20:08:21 2019 [246704]   12632       13148       STREAM-OP           HIGH        Error (-22) in AddStream (LASTX,/ES:XCME,2000)
Sun Feb 03 20:08:23 2019 [280662]   12632       13148       STREAM              HIGH        error creating new topic stream, ERROR# -22
Sun Feb 03 20:08:27 2019 [839305]   12632       13148       STREAM-OP           HIGH        Error (-22) in AddStream (LASTX,/ZN:XCBT,2000)

service-log
DATE / TIME                         Process ID  Thread ID   Log TAG             Severity    Description

Sun Feb 03 20:03:32 2019 [780066]   7636        196         STARTUP             LOW         lpCmdLn: 
Sun Feb 03 20:03:32 2019 [781561]   7636        196         STARTUP             LOW         argc: 0 custom_session: -1 admin_pos: 0 no_service_pos: 0
Sun Feb 03 20:03:32 2019 [782559]   7636        6264        ADMIN               LOW         successfully registered control handler
Sun Feb 03 20:03:32 2019 [782559]   7636        6264        STATE               LOW         SERVICE_START_PENDING 
Sun Feb 03 20:03:32 2019 [782559]   7636        6264        STARTUP             LOW         start tos-databridge-engine.exe (AS A SERVICE)
Sun Feb 03 20:03:32 2019 [783093]   7636        6264        SPAWN               LOW         (4) set session id: 2 (this may may fail during (6) 'CreateProcessAsUser')
Sun Feb 03 20:03:32 2019 [805516]   7636        6264        STATE               LOW         SERVICE_RUNNING

**Comment by xyang5987** [comment]
I checked the tasklist. It contains the lines

tos-databridge-serv-x64.e     7636 Services                   0      4,924 K
tos-databridge-engine-x64    12632 Console                    2      6,820 K
thinkorswim.exe              13260 Console                    2    796,168 K

It looks service and engine in the different sessions. What should I do to resolve this?

Thanks

Xuefeng

**Comment by jeog** [comment]
You need to reinstall with the custom the custom session arg - use the session # of thinkorswim.exe. [See steps 5 and 6.](https://github.com/jeog/TOSDataBridge/blob/master/README_INSTALL.md#installation-details)
