### ISSUE TITLE
No errors - no connection

### ISSUE THREAD

**Issue by SCUrrutia** [jeog/TOSDataBridge#16]
Hi there,

I've tried to start the bridge service via 'SC start TOSDataBridge' but cannot seem to connect. Any ideas how I can troubleshoot? I don't have anti virus on my machine.

![capture](https://user-images.githubusercontent.com/47764816/52985244-f9d90e80-33c0-11e9-9e8e-79873018d2c6.PNG)

**Comment by jeog** [comment]
The service seems to be working. You can confirm with ```SC query TOSDataBridge``` 

What errors do you get when you try to connect from the client library?

**Comment by alienclaster** [comment]
I have the similar situation. Service do not starts. After SC start TOSDataBridge and then SC query TOSDataBridge i have: STATE : 1  STOPPED and can't start it even manually throught the services.msc. I'v tried to reinstall with tosdb-setup.bat x64 and with admin user: tosdb-setup.bat x64 admin. Nothing helps.

Sometimes i receive this message: [SC] StartService: error: 1053:
The service did not respond to the start or control request in a timely fashion.

machine: Windows 7 64bit, Python 3 x64.
