### ISSUE TITLE
Service don't start

### ISSUE THREAD

**Issue by alienclaster** [jeog/TOSDataBridge#17]
Hi!

I can't run the service. My actions:

1. tosdb-setup.bat x64
2. SC start TOSDataBridge
3. SC query TOSDataBridge

Result: STATE : 1 STOPPED.

I can't start it even manually through the "services.msc".

When I try to install with "tosdb-setup.bat x64 xzvf" (xzvf is my current user with admin privileges, the only one user in the system) and then "SC start TOSDataBridge". After this command in Task Manager appears for a while and then disappears the process "tos-databridge-serv-x64.exe" and after it disappears in console I have error:

[SC] StartService: error: 1053:
The service did not respond to the start or control request in a timely fashion.

Tried to set up in service options "Allow Service to Interact with Desktop"... Nothing helps :(

machine: Windows 7 64bit, Python 3 x64.

**Comment by jeog** [comment]
please post the contents of log/service-log.log

**Comment by alienclaster** [comment]
After:
* tosdb-setup.bat x64
* SC start TOSDataBridge
* SC query TOSDataBridge

-- service-log.log:

DATE / TIME                         Process ID  Thread ID   Log TAG             Severity    Description

Sat Feb 23 01:05:49 2019 [56898]    1212        5344        STARTUP             LOW         lpCmdLn: 
Sat Feb 23 01:05:49 2019 [57898]    1212        5344        STARTUP             LOW         argc: 0 custom_session: -1 admin_pos: 0 no_service_pos: 0
Sat Feb 23 01:05:49 2019 [58898]    1212        1216        ADMIN               LOW         successfully registered control handler
Sat Feb 23 01:05:49 2019 [59898]    1212        1216        STATE               LOW         SERVICE_START_PENDING 
Sat Feb 23 01:05:49 2019 [59898]    1212        1216        STARTUP             LOW         start tos-databridge-engine.exe (AS A SERVICE)
Sat Feb 23 01:05:49 2019 [60899]    1212        1216        SPAWN               HIGH        (3a) failed to lookup Mandatory Level group, ERROR# 1332
Sat Feb 23 01:05:49 2019 [60899]    1212        1216        STARTUP             HIGH        failed to spawn D:\TOSDataBridge-master\bin\Release\x64\tos-databridge-engine-x64.exe --spawned --service
Sat Feb 23 01:05:49 2019 [61899]    1212        1216        STATE               LOW         SERVICE_STOPPED 
Sat Feb 23 01:05:49 2019 [61899]    1212        5344        SHUTDOWN            LOW         service exiting

**Comment by jeog** [comment]
before we go any further run the setup script w/ the admin switch (not the user name) and see what happens:
```C:\TOSDataBridge\> tosdb-setup.bat x64 admin```

**Comment by alienclaster** [comment]
D:\TOSDataBridge-master>tosdb-setup.bat x64 admin
...
+ Creating TOSDataBridge Service ...
+ D:\TOSDataBridge-master\\bin\\Release\\x64\\tos-databridge-serv-x64.exe --admin
[SC] CreateService: success

D:\TOSDataBridge-master>sc start TOSDataBridge

SERVICE_NAME: TOSDataBridge
        TYPE                : 10  WIN32_OWN_PROCESS
        STATE          : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE   : 0  (0x0)
        SEVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT  : 0x0
        WAIT_HINT           : 0x7d0
        PROCESS_ID        : 8776
        FLAGS              :

D:\TOSDataBridge-master>sc query TOSDataBridge

SERVICE_NAME: TOSDataBridge
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

-- service-log.log:

DATE / TIME                         Process ID  Thread ID   Log TAG             Severity    Description

Sat Feb 23 07:42:44 2019 [238404]   8776        4616        STARTUP             LOW         lpCmdLn: --admin        
Sat Feb 23 07:42:44 2019 [238404]   8776        4616        STARTUP             LOW         argc: 1 custom_session: -1 admin_pos: 1 no_service_pos: 0
Sat Feb 23 07:42:44 2019 [240405]   8776        6324        ADMIN               LOW         successfully registered control handler
Sat Feb 23 07:42:44 2019 [245405]   8776        6324        STATE               LOW         SERVICE_START_PENDING 
Sat Feb 23 07:42:44 2019 [245405]   8776        6324        STARTUP             LOW         start tos-databridge-engine.exe (AS A SERVICE)
Sat Feb 23 07:42:44 2019 [246405]   8776        6324        SPAWN               HIGH        (3a) failed to lookup Mandatory Level group, ERROR# 1332
Sat Feb 23 07:42:44 2019 [246405]   8776        6324        STARTUP             HIGH        failed to spawn D:\TOSDataBridge-master\bin\Release\x64\tos-databridge-engine-x64.exe --spawned --service
Sat Feb 23 07:42:44 2019 [249405]   8776        6324        STATE               LOW         SERVICE_STOPPED 
Sat Feb 23 07:42:44 2019 [249405]   8776        4616        SHUTDOWN            LOW         service exiting

**Comment by jeog** [comment]
The problem is occurring when the service tries to spawn the engine. LookupAccountName for "High Mandatory Level" is returning an error indicating there's something wrong w/ that account name. I've never seen this problem w/ the service so my guess is there is something specific with your setup that isn't accounted for in the SpawnRestrictedProcess(..) function used by the service.

Are you running a non-english version of windows by chance? Anything about the machine's group/security policy that you can think of that may be unique? Have you enable/disabled any security features etc.

One thing to try: ```C:\> whoami /groups```
and look to see if there's a group name w/ 'Mandatory Label' or 'Mandatory Level' in it

**Comment by alienclaster** [comment]
> Are you running a non-english version of windows by chance?

Right. It's russian language version of Windows.

> Anything about the machine's group/security policy that you can think of that may be unique?

Here is my C++ compilers and .net framework version:

![cpp_versions_1](https://user-images.githubusercontent.com/904795/53307842-0f5ca580-38a5-11e9-92b3-f0cf8ff0941b.png)

> Have you enable/disabled any security features etc.

I have disabled UAC.

> C:\> whoami /groups

![dtb_1](https://user-images.githubusercontent.com/904795/53307868-4c289c80-38a5-11e9-88a7-3797d493ed49.png)

> and look to see if there's a group name w/ 'Mandatory Label' or 'Mandatory Level' in it

On the screenshot "Обязательная группа" translates like "Mandatory Level". There are several mandatory level groups:

- NT Authority / Локальная учетная запись и член группы "Администраторы" (NT Authority / local account and member of administrators group)
- BUILTIN / Администраторы (BUILTIN / Administrators)
- BUILTIN / Пользователи (BUILTIN / Users)
- NT Authority / ИНТЕРАКТИВНЫЕ (NT Authority / Interactive)

- NT Authority / Прошедшие проверку (NT Authority / Authenticated)
- NT Authority / Данная организация (NT Authority / Current organizatiion)
- NT Authority / Локальная учетная записать (NT Authority / Local account)

- NT Authority / Проверка подлинности NTLM (NT Authority/ NTLM authentication)
- Обязательная метка / Высокий обязательный уровень (Mandatory label / High Mandatory Level)

> and look to see if there's a group name w/ 'Mandatory Label' or 'Mandatory Level' in it

In this way, it seems the last one is "Mandatory label / High Mandatory Level" but in the system it has only russian name. May be the problem is because of that? Is there is some solution?

**Comment by jeog** [comment]
My first guess is there is a problem with how the string literal is being encoded and it can't find that account name during the lookup. If you're using the precompiled binary you can try using VisualStudio to build the library yourself and see if that helps.

**Comment by automated-trading** [comment]
I am having the same issue. The service stops as soon as you start it. 
![error](https://user-images.githubusercontent.com/25007322/53713735-e8105600-3e19-11e9-84a8-4a09f76ee515.png)

**Comment by automated-trading** [comment]
service-log
---------------------------------------------------------
Mon Mar 04 01:12:29 2019 [632614]   3988        1804        STARTUP             LOW         lpCmdLn: 
Mon Mar 04 01:12:29 2019 [633614]   3988        1804        STARTUP             LOW         argc: 0 custom_session: -1 admin_pos: 0 no_service_pos: 0
Mon Mar 04 01:12:29 2019 [636614]   3988        7144        ADMIN               LOW         successfully registered control handler
Mon Mar 04 01:12:29 2019 [636614]   3988        7144        STATE               LOW         SERVICE_START_PENDING 
Mon Mar 04 01:12:29 2019 [636614]   3988        7144        STARTUP             LOW         start tos-databridge-engine.exe (AS A SERVICE)
Mon Mar 04 01:12:29 2019 [637614]   3988        7144        SPAWN               LOW         (4) set session id: 1 (this may may fail during (6) 'CreateProcessAsUser')
Mon Mar 04 01:12:29 2019 [649615]   3988        7144        STATE               LOW         SERVICE_RUNNING 
Mon Mar 04 01:12:31 2019 [649729]   3988        7144        SHUTDOWN            HIGH        service believes engine closed unexpectedly
Mon Mar 04 01:12:31 2019 [649729]   3988        7144        SHUTDOWN            HIGH        service believes engine has shutdown
Mon Mar 04 01:12:31 2019 [651730]   3988        7144        STATE               LOW         SERVICE_STOPPED 
Mon Mar 04 01:12:31 2019 [651730]   3988        1804        SHUTDOWN            LOW         service exiting

**Comment by jeog** [comment]
This appears to be a different issue as the engine is spawned but then is killed. First, check your anti-virus software is not killing/quarantining the engine(should get logged by the AV software). Some AV heuristics consider the startup behavior suspicious.

**Comment by konstantin-aisc** [comment]
> My first guess is there is a problem with how the string literal is being encoded and it can't find that account name during the lookup. If you're using the precompiled binary you can try using VisualStudio to build the library yourself and see if that helps.

I have the same problem on a Russian language system. Please direct me to docs on building myself using Visual Studio?

**Comment by jeog** [comment]
[There's a few notes in the main readme](https://github.com/jeog/TOSDataBridge/blob/master/README.md#build-optional).

You should just be able to open VisualStudioBuild/tos-databridge.sln file directly in VS, select the build type(x64 or x86 release) by right clicking on the solution or using the main menu, click build, and follow the original install instructions.

Just double-check that the install script is finding the fresh binary instead of the precompiled, maybe delete the original(s) from the bin folders before you build to be sure.

Let me know how it goes.

**Comment by konstantin-aisc** [comment]
@jeog it was most definitely related to the OS language, just as you suggested. I have installed English version of Windows 10 and everything works right out of the box. Thanks!

**Comment by jeog** [comment]
Good to know, glad you got it working.

If you get a chance, and it's not too much trouble, I'd be interested to know if building on a Russian language system fixes the problem (or creates new problems).

**Comment by konstantin-aisc** [comment]
I cannot check any more, as I now only have an English language system. But I had a lot of errors, when I was trying to build it (see screenshots).

But I think it will only build in 2012 Studio, and only one by one.

![photo5348388719645797036](https://user-images.githubusercontent.com/45392818/57038927-2dd67880-6c29-11e9-858c-f0422ded3918.jpg)
![photo5350327266019748478](https://user-images.githubusercontent.com/45392818/57038928-2dd67880-6c29-11e9-8487-efa05d39c4da.jpg)

**Comment by jeog** [comment]
No problem, thanks for the feedback.
