### ISSUE TITLE
data not being pulled

### ISSUE THREAD

**Issue by ccalo13** [jeog/TOSDataBridge#19]
so i was following the tutorial and was able to get everything setup with no problems and the connections be successful.
but when it came to printing the data, i can't get it to pull the data from TOS. went through all the troubleshooting steps and everything seems to be in check. 

![Untitled](https://user-images.githubusercontent.com/50596702/57649608-b85a9880-7596-11e9-88b8-1149bf687733.png)

tried running ToS as administrator but that makes the ToS connection fail even though its remains on the same session as the databridge. below are the logs.

![Untitled2](https://user-images.githubusercontent.com/50596702/57650356-9cf08d00-7598-11e9-867e-cc5e14aa2d67.png)

client:
DATE / TIME                         Process ID  Thread ID   Log TAG             Severity    Description

Mon May 13 15:55:29 2019 [23355]    11476       12680       IPC                 LOW         connected to engine, client: C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe
Mon May 13 15:55:30 2019 [540341]   11476       12680       ENGINE              HIGH        error code returned from engine: -22

engine:
DATE / TIME                         Process ID  Thread ID   Log TAG             Severity    Description

Mon May 13 15:55:16 2019 [370447]   9404        11328       STARTUP             LOW         is_service == true
Mon May 13 15:55:16 2019 [371447]   9404        11328       STARTUP             LOW         lpCmdLn args: --spawned --service 
Mon May 13 15:55:16 2019 [381449]   9404        11328       STARTUP             LOW         entering RunMainCommLoop

service:
DATE / TIME                         Process ID  Thread ID   Log TAG             Severity    Description

Mon May 13 15:55:16 2019 [332447]   6992        10980       STARTUP             LOW         lpCmdLn: 
Mon May 13 15:55:16 2019 [333448]   6992        10980       STARTUP             LOW         argc: 0 custom_session: -1 admin_pos: 0 no_service_pos: 0
Mon May 13 15:55:16 2019 [334448]   6992        4864        ADMIN               LOW         successfully registered control handler
Mon May 13 15:55:16 2019 [334448]   6992        4864        STATE               LOW         SERVICE_START_PENDING 
Mon May 13 15:55:16 2019 [334448]   6992        4864        STARTUP             LOW         start tos-databridge-engine.exe (AS A SERVICE)
Mon May 13 15:55:16 2019 [335448]   6992        4864        SPAWN               LOW         (4) set session id: 1 (this may may fail during (6) 'CreateProcessAsUser')
Mon May 13 15:55:16 2019 [358447]   6992        4864        STATE               LOW         SERVICE_RUNNING

**Comment by jeog** [comment]
If you're trying to access data immediately after you connect it's possible nothing is available yet in the buffers.  Import the time library and before accessing any data add ```time.sleep(3)``` and see if you get something.

**Comment by ccalo13** [comment]
Gotcha. that worked. thanks
