### ISSUE TITLE
Cannot connect to ThinkorSwim

### ISSUE THREAD

**Issue by zxcvbn97** [jeog/TOSDataBridge#2]
Hi there,

I tried both 0.5, 0.6 and 0.7 (the latest version). I could get TOSDataBridge service to run, but cannot connect to ThinkorSwim. I used the latest ThinkorSwim version. 

Please help!

![image](https://cloud.githubusercontent.com/assets/9757976/23538101/4a7960f8-ff96-11e6-9f85-a6936d33b3f3.png)

**Comment by jeog** [comment]
1. let me know what happens when you init(...) the same way (in version 0.7) and call tosdb.connection_state()

2. paste the log info from log/client-log.log, log/engine-log.log, and log/service-log.log (just the relevant entries around the time you tried this).

**Comment by zxcvbn97** [comment]
tosdb.connection_state() returns 1.

Here are the logs! Thanks!


DATE / TIME                         Process ID  Thread ID   Log TAG             Severity    Description

Fri Mar 03 04:09:13 2017 [358741]   2552        2484        STARTUP             LOW         is_service == true
Fri Mar 03 04:09:13 2017 [360694]   2552        2484        STARTUP             LOW         lpCmdLn args: --spawned --service 
Fri Mar 03 04:09:13 2017 [369510]   2552        2484        STARTUP             LOW         entering RunMainCommLoop
Fri Mar 03 04:10:38 2017 [42380]    2552        2484        SERVICE-MSG         LOW         TOSDB_SIG_STOP message received
Fri Mar 03 04:10:38 2017 [43350]    2552        2484        SHUTDOWN            LOW         exiting MainCommLoop
Fri Mar 03 04:10:38 2017 [43350]    2552        2484        CONTROL             HIGH        out of run loop (remove all streams, clean up)
Fri Mar 03 04:10:38 2017 [43350]    2552        2484        SHUTDOWN            HIGH        engine exiting
Fri Mar 03 04:10:39 2017 [799182]   2748        3572        STARTUP             LOW         is_service == true
Fri Mar 03 04:10:39 2017 [801167]   2748        3572        STARTUP             LOW         lpCmdLn args: --spawned --service 
Fri Mar 03 04:10:39 2017 [810883]   2748        3572        STARTUP             LOW         entering RunMainCommLoop



DATE / TIME                         Process ID  Thread ID   Log TAG             Severity    Description

Fri Mar 03 04:09:13 2017 [326495]   2548        2128        STARTUP             LOW         lpCmdLn: --admin        
Fri Mar 03 04:09:13 2017 [328476]   2548        2128        STARTUP             LOW         argc: 1 custom_session: -1 admin_pos: 1 no_service_pos: 0
Fri Mar 03 04:09:13 2017 [331414]   2548        3720        ADMIN               LOW         successfully registered control handler
Fri Mar 03 04:09:13 2017 [331414]   2548        3720        STATE               LOW         SERVICE_START_PENDING 
Fri Mar 03 04:09:13 2017 [331414]   2548        3720        STARTUP             LOW         start tos-databridge-engine.exe (AS A SERVICE)
Fri Mar 03 04:09:13 2017 [332387]   2548        3720        SPAWN               LOW         (4) set session id: 1 (this may may fail during (6) 'CreateProcessAsUser')
Fri Mar 03 04:09:13 2017 [340233]   2548        3720        STATE               LOW         SERVICE_RUNNING 
Fri Mar 03 04:10:38 2017 [42380]    2548        2128        STATE               LOW         SERVICE_STOP_PENDING 
Fri Mar 03 04:10:39 2017 [383187]   2548        3720        SHUTDOWN            HIGH        service believes engine has shutdown
Fri Mar 03 04:10:39 2017 [385116]   2548        3720        STATE               LOW         SERVICE_STOPPED 
Fri Mar 03 04:10:39 2017 [385116]   2548        2128        SHUTDOWN            LOW         service exiting
Fri Mar 03 04:10:39 2017 [774770]   3536        3284        STARTUP             LOW         lpCmdLn: --admin        
Fri Mar 03 04:10:39 2017 [776699]   3536        3284        STARTUP             LOW         argc: 1 custom_session: -1 admin_pos: 1 no_service_pos: 0
Fri Mar 03 04:10:39 2017 [778674]   3536        2320        ADMIN               LOW         successfully registered control handler
Fri Mar 03 04:10:39 2017 [779667]   3536        2320        STATE               LOW         SERVICE_START_PENDING 
Fri Mar 03 04:10:39 2017 [779667]   3536        2320        STARTUP             LOW         start tos-databridge-engine.exe (AS A SERVICE)
Fri Mar 03 04:10:39 2017 [780650]   3536        2320        SPAWN               LOW         (4) set session id: 1 (this may may fail during (6) 'CreateProcessAsUser')
Fri Mar 03 04:10:39 2017 [783550]   3536        2320        STATE               LOW         SERVICE_RUNNING

**Comment by jeog** [comment]
1. You posted service-log and engine-log; am I right to assume there's nothing in client-log? What about after you tried the connection_state() call?

2. I realize this is probably a dumb question, but you do have the TOS platform running while you used connected()/connection_state(), right?

**Comment by zxcvbn97** [comment]
1. client-log is empty. 

2. connection_state() returns False
![image](https://cloud.githubusercontent.com/assets/9757976/23575138/12f6fc68-004e-11e7-981a-b920630a13c2.png)

3. I already started TOS and logged in to my TOS. 

Could that be a permission issue?

**Comment by jeog** [comment]
It may be. What's a bit strange is that when the underlying C lib fails to get a good connection it should log it in client-log.log. When I try to replicate it (by shutting TOS off or running it with higher privileges than the engine) I get an error message ('error code returned from engine: -22') sent to client-log.log. Looking through the source I can't immediately find a way *that* call can fail without sending a log message UNLESS the connection mechanism (between python and the engine) fails, but *that* should be logged as well.

Before going to the next step let's try one more time from the beginning, just to be sure we're not missing something obvious:

1. stop the service and the python session 
2. open up task manager or resource manager and check there isn't a 'tos-databridge-engine-x64.exe' still running (if it is let me know and kill it manually)
3. delete all the log files
4. run the tosdb-setup.bat script again
5. start the service and TOS again
6. open python, import tosdb, call init(...) like you did before
7. call connection_state() a bunch of times to be sure it's still returning CONN_ENGINE (1)
8. try to create a block:  
```
    block = tosdb.TOSDB_DataBlock()
```
9. add an item and topic (the latter should raise an exception)
```
    block.add_items('spy')
    block.add_topics('LAST')
```
10. let me know of any exceptions you receive  (the type and message)
11. paste everything from all the logs

If everything looks the same you can get started on the next step to determine if we have an integrity level/session issue:

1. [download sysinternals from microsoft](https://technet.microsoft.com/en-us/sysinternals/bb842062.aspx)
2. run procexp.exe with admin privileges
3. go to view -> select columns -> check 'Session' and 'Integrity Level'
4. let me know those values for both tos-databridge-engine-x64.exe and thinkorswim.exe

btw, what version of Windows are you using?

**Comment by zxcvbn97** [comment]
It seems like thinkorswim (session 2) and tos-databridge-engine-x64.exe (session 1) are running under different sessions. I am using Windows server 2012 on a cloud provider and accessing this windows instance remotely. Is there any way to force them to run under the same session? 

![image](https://cloud.githubusercontent.com/assets/9757976/23616092/306fa2e8-024e-11e7-8d9f-b220a22a443a.png)

**Comment by jeog** [comment]
Yes, run the setup script with the custom session:
```
(Admin) C:/TOSDataBridge/> tosdb-setup.bat x64 admin 2
```
that should do it

**Comment by zxcvbn97** [comment]
Nice, it works now. How do you think this compares with Interactive Brokers API?

**Comment by jeog** [comment]
Not sure, I never used it. 

Just keep in mind this is much more limited than an API a brokerage may provide, it simply pulls data off the platform via Window's Dynamic Data Exchange and provides an interface to access it in a raw form. What you get and when you get it really depends on how TOS exports it, not necessarily what you see, tick-by-tick, on the screen. Check out [README_DETAILS](../blob/master/README_DETAILS.md) for more info.
