### ISSUE TITLE
Pull Pos Qty from TOS

### ISSUE THREAD

**Issue by shivamdpat94** [jeog/TOSDataBridge#22]
Hello,

I've successfully connected to TOSDB and have integrated Custom quotes into my python code. I would like to also add "Pos Qty" from the marketwatch/quotes tab as well. It can be added to the table as a column but is not a Custom Quote. It is a Porfolio type instead. It may also go by the name "POSITION_QTY". In the meta_enum.py file, I have looked through the possible topics by looking into dir(cls) on line 124. I do not see anything like Pos Qty as a possible topic. I would like to be able to import data from TOS showing me my share sizes for each stock in the Marketwatch/quotes section. Is this possible using TOSDB?

**Comment by jeog** [comment]
The topics listed are the only ones available. The only other way to do this would be to access the data through a CUSTOM quote. I believe there is a function for this in thinkscript that you can try using inside a CUSTOM quote script: https://tlc.thinkorswim.com/center/reference/thinkScript/Functions/Portfolio/GetQuantity

**Comment by shivamdpat94** [comment]
I've given that a try but it appears Portfolio functions such as GetQuotes() is not a callable function in custom quotes. I'm able to use the function in thinkscript when creating an indicator but not in thinkscript when developing a Custom Quote. I am assuming then that there is no way for my python program to be aware of my Portolio size as it is running.

**Comment by jeog** [comment]
Looks that way. You can always use the [TDMA API](https://github.com/jeog/TDAmeritradeAPI) directly - but that's significantly more work.
