### ISSUE TITLE
Potential Options Paradise

### ISSUE THREAD

**Issue by caspersauce** [jeog/TOSDataBridge#25]
This is a fantastic library, works great and gives the data needed. There is a lot of potential here when working with options. Is it possible to get strikes and expirations for a symbol? That would be incredibly useful for populating the right items into add_items.

I also know that it has been mentioned in the past, but is there anyway to set the time? The thinkback feature of TOS is very powerful and gives access to a ton of info from the past. If not, do you have any ideas how to implement it?

**Comment by jeog** [comment]
As far as I know there isn't a way to get strikes/exps but you can check to see if there is a function in ThinkScript.

I don't believe there is any way to interact w/ thinkback. TOSDB is pretty low-level (not accessing any type of API) and just pulls whatever TOS will exports via DDE.

**Comment by caspersauce** [comment]
That is what I had figured. Thanks for the response!
