### ISSUE TITLE
No module named 'tosdb' ERROR

### ISSUE THREAD

**Issue by hunterkrisp** [jeog/TOSDataBridge#29]
I continue to get a ModuleNotFoundError when importing tosdb, tried pip install as well with no avail, any suggestions?

**Comment by jeog** [comment]
Did you follow the instructions in the [install section](https://github.com/jeog/TOSDataBridge/blob/master/README_PYTHON.md#install)?

**Comment by hunterkrisp** [comment]
Yup, got the C modules downloaded, had the setup.py install successfully
download through admin command line, server is on same session ID as TOS,
only problem is I can’t seem to get the module tosdb imported.

**Comment by jeog** [comment]
can you paste the commands you're using and the output you're seeing during install

anything non-standard about your python environment? what python version are you using?
