### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by fjafferi** [jeog/TOSDataBridge#3]
I am getting the following message using python:
Failed to Connect to TOS

Do you have any steps on how to debug this?

Thanks!

**Comment by fjafferi** [comment]
if it helps, here is the message from logs:
error code returned from engine: -21

**Comment by jeog** [comment]
Please post the full contents of client-log.log and engine-log.log (at least all the messages you received during the last time you tried to init/connect, even if they don't appear to be relevant).

What branch/version are you using? 

Is there anything particularly non-standard about your system or how TOS is being run i.e custom privileges/permissions, accessing remotely, restrictive anti-virus/IDS settings etc? Are you running the TOS platform with administrative privileges or as a standard user?

**Comment by fjafferi** [comment]
Attaching the zipped log folder.
[log.zip](https://github.com/jeog/TOSDataBridge/files/1184169/log.zip)

I am using the latest master branch.

no provileges/permissions, I even have windows UAC disabled, so it doesn't prompt me when I start up ToS.

Thank you for your help!

**Comment by jeog** [comment]
error code -22 and -21 both have to do with DDE (how the engine and TOS communicate via windows). Generally this is because of inadequate permissions for the client; a session mismatch between the service and TOS; IPC timeout; or some other system level mechanism blocking the IPC. When you ran the setup script with the -admin switch it went from returning -22 to -21, indicating that the communication was partly successful. It's possible that indicates a bug in service/engine.cpp but let's try a few things first:

Try connecting via the shell:
1) make sure the service and TOS is running; be sure to have passed -admin to the setup script
2) run the tos-databridge-shell program from the /bin folder 
3) enter the follow commands:
    [--> Connect
    [--> IsConnectedToEngineAndTOS
4) let me know if the second command returns true or false, and copy/paste the new log messages from client-log.log

IF it returns 'true'  run the setup script WITHOUT the -admin switch, start the Service/TOS and follow steps 2 through 4 again.

Also, you should make sure that the engine and TOS are running in the same session. Run 'tasklist' from the command line and let me know what's in the session# field for the tos-databridge-serv, tos-databridge-engine, and thinkorswim processes.

**Comment by fjafferi** [comment]
IsConnectedToEngineAndTOS returned false, so I tried the commands your sent. Here is the engine-log output:

`Sat Jul 29 05:55:44 2017 [812901]   6788        5480        SERVICE-MSG         LOW         TOSDB_SIG_STOP message received
Sat Jul 29 05:55:44 2017 [812901]   6788        5480        SHUTDOWN            LOW         exiting MainCommLoop
Sat Jul 29 05:55:44 2017 [812901]   6788        5480        CONTROL             HIGH        out of run loop (remove all streams, clean up)
Sat Jul 29 05:55:44 2017 [812901]   6788        5480        SHUTDOWN            HIGH        engine exiting
Sat Jul 29 05:57:20 2017 [246381]   4412        3896        STARTUP             LOW         is_service == true
Sat Jul 29 05:57:20 2017 [247385]   4412        3896        STARTUP             LOW         lpCmdLn args: --spawned --service 
Sat Jul 29 05:57:20 2017 [259383]   4412        3896        STARTUP             LOW         entering RunMainCommLoop
Sat Jul 29 06:01:36 2017 [645115]   4412        3896        STREAM              HIGH        error creating new topic stream, ERROR# -21
Sat Jul 29 06:01:36 2017 [645115]   4412        3896        STREAM-OP           HIGH        Error (-21) in AddStream (LAST,SPY,10000)
`

Here is the client-log output:

`Sat Jul 29 05:56:55 2017 [478960]   5012        5356        IPC                 HIGH        timed out waiting for aware_of_connection
Sat Jul 29 05:56:55 2017 [479959]   5012        5356        IPC                 LOW         NOT connected to engine, client: C:\Users\admin\TOSDataBridge\bin\Release\x64\tos-databridge-shell-x64.exe
Sat Jul 29 05:58:01 2017 [391756]   7700        7864        IPC                 LOW         connected to engine, client: C:\Users\admin\TOSDataBridge\bin\Release\x64\tos-databridge-shell-x64.exe
Sat Jul 29 05:58:19 2017 [996829]   7700        7864        ENGINE              LOW         error code returned from engine: -21
Sat Jul 29 06:01:36 2017 [645115]   7700        7864        ENGINE              LOW         error code returned from engine: -21
`

**Comment by fjafferi** [comment]
tasklist:

thinkorswim.exe                676 Console                    1    633,536
tos-databridge-serv-x64.e     4124 Services                   0      4,880 K
tos-databridge-engine-x64     4412 Console                    1      6,800 K

**Comment by jeog** [comment]
1) If you have an anti-virus running check the logs to see if its blocking anything for the engine and/or TOS. (You can try temporarily disabling it and see if it works.)

2) Try running the x86 version, run the Connect/IsConnectedToEngineAndTOS commands in the shell and see if you get same result

What version of Windows are you on ?
Where is the thinkorswim.exe located on your system?

My best guess is we have some kind of privilege issue between the engine and TOS. When I get a chance later I'll push a new branch that will add a bunch of logging calls to see if we can figure out exactly what Sys call is causing the problem, and what error code it's generating.

**Comment by fjafferi** [comment]
1, I don't have anti-virus running.
2, X86 works, both commands return true now. However, when i try to init in python, looks like its trying to connect to x64 version instead of x86 and it fails.

I am running Windows 10 Home X64

**Comment by jeog** [comment]
Ya, that seems to indicate a bug in the engine; maybe Win10 changed an implementation detail that I was (stupidly) relying on. I'll try to replicate on a Win10 machine and see if I can figure it out. If I can't I'll push a new branch that will try to log more error details.

In the meantime you can always download a 32bit version of python and use that. (you may want to google installing 32bit and 64bit python side by side to avoid any ENVIRONMENT issues; I have about a half-dozen versions side by side with no problem) 

Lastly, just check the JRE: from the command line navigate to the folder that has thinkorswim.exe, enter 'jre\bin\java -version' and paste the results.

**Comment by jeog** [comment]
this should be fixed as of commit: 8543c9a4d842061294884b26623c244b1bff7164 , only on branch [issue-3-a](https://github.com/jeog/TOSDataBridge/tree/issue-3-a) for now.

looks like I was mistakenly casting an 8 byte pointer to a 4 byte int which created an invalid message that wasn't returned to the engine; older versions of 64 bit windows didn't necessarily provide an address that was effected by the narrowing so it never got caught.

let me know how it goes, I'll push it to master sometime next week after I have some time to test it during market hours.
