### ISSUE TITLE
Missing Topic (java)?

### ISSUE THREAD

**Issue by digitalml** [jeog/TOSDataBridge#35]
Was hoping to get profit and loss for a current position with this but it seems that the "P_L_PERCENT" topic is not available? Is that due to TOS or the Bridge please?

Thank you.

**Comment by jeog** [comment]
I believe that's a limitation of TOS. The topic list was originally setup with every field they exported. 

Thinkscript has some functions like 'GetOpenPL' that you way be able to use inside a CUSTOM topic: https://github.com/jeog/TOSDataBridge/blob/master/README_DETAILS.md#custom-topics
