### ISSUE TITLE
Possible to get Stock Live News information

### ISSUE THREAD

**Issue by Paw2Pom** [jeog/TOSDataBridge#36]
Is it possible to get News Information for specific stock/ticker?

<img width="1276" alt="TOS News" src="https://user-images.githubusercontent.com/21134942/135012002-ba156573-cb3f-4d71-8006-4fbc95eae39d.png">

**Comment by jeog** [comment]
There is a MT_NEWS topic that you can try, but not sure what it returns.

Alternatively, the TDMA API let's you stream news headlines.
