### ISSUE TITLE
Failure to import tosdb module

### ISSUE THREAD

**Issue by Theaxx** [jeog/TOSDataBridge#5]
Hi. 

Strangely after upgrade to python 3.6. I am unable to run the script with the failure that tosdb module is not found. I have managed to import and run it previously. Is there some compatibility issues with 3.6? Or suggest next steps to troubleshoot as the script managed to run previously.

**Comment by jeog** [comment]
Did you use the 'upgrade' feature from the (windows) python installer or did you manually install v3.6 in a new location? 

In python try:
```
>>> import importlib
>>> importlib.find_loader('tosdb')
```

If that returns 'None' it indicates that, for some reason, the package is missing. Re-installing (...TOSDataBridge/python/python setup.py install) should fix it.

**Comment by Theaxx** [comment]
hello. I used the upgrade feature, when I key in hte code in python, I did not receive a result (positive or negative)

**Comment by Theaxx** [comment]
anyway how do i reinstall the package because when I tried it, it appears to have an unexpected error when i ran tosdb setup bat. It failed, likely because I already have the current package installed already

Is there a way to wipe out the previous installation clean and reinstall again using your method to unzip the package and run setup bat.

**Comment by jeog** [comment]
tosdb-setup.bat has nothing to do w/ the python package, it installs the backend Windows Service that all the different interfaces(C/C++, Java, Python) interact with via the tos-databridge DLL. 

All you need to do to reinstall the python package is:
`C:\...TOSDataBridge\python\python setup.py install`

[You should review the installation details.](https://github.com/jeog/TOSDataBridge/blob/master/README_INSTALL.md)

**Comment by Theaxx** [comment]
Thanks! it worked for me.
