### ISSUE TITLE
Tutorial clarification

### ISSUE THREAD

**Issue by Theaxx** [jeog/TOSDataBridge#6]
Hi, I tried going through the tutorial you provided. I could follow until the last portion, where I bumped into a definition error which d is not defined. I tried looking through myself and indeed, d was not defined apriori, but then is used as part of the loop code. Tks!

**Comment by jeog** [comment]
The only 'd' variable I see is one implicitly defined by the for loop:

    >>> for _ in range(1):
    >>>    ...
    >>>    for d in [get1] + snapshot1 + snapshot2:
    >>>        print(d)

Are you talking about a different 'd'? Do you have a typo? Are you copying the tutorial code correctly? Paste the code that caused the definition error.

**Comment by Theaxx** [comment]
for _ in range(1):
    get1 = block1.get("SPY", "Last", date_time=True, indx=0)
    time.sleep(3)
    snapshot1= blssfm("SPY", "Last", date_time=True, beg=0)
    time.sleep(8)
    snapshot2 = blssfm("SPY","Last", date_time=True, beg=0)
    snapshot1.reverse()
    snapshot2.reverse()
    for d in [get1] + snapshot1 + snapshot2:
        print(d)

**Comment by jeog** [comment]
1) As long as the 'd' isn't used outside of that inner 'for' loop you shouldn't get a definition error.

2) The second problem can occur if you're a) using invalid symbols, or b) **immediately trying to get data out of the stream/block before any has been inserted**. It might take a few 100 milliseconds after adding items and topics for initial data to get into the stream/block. The '0's indicate undefined data, empty streams in this case. The 'get' call will throw TOSDB_DataError if there's no data at the requested index yet. (0 is the default index value, so the default call will throw if its stream is empty.) 

    The easiest ways to avoid this:  
    - wait a second or two after adding adding a new item or topic before pulling data
    - check that block.stream_occupancy(item,topic) > 0 before trying to get data
    - deal w/ the exception or undefined data, wait and try again
    - use .stream_snapshot(...) instead or .get(...) and check if it returns an empty list, wait and try again if it does

    If it's still returning all 0's after waiting a few seconds paste the code you're using.

**Comment by Theaxx** [comment]
Hi, Does not work. Using this code

import tosdb

tosdb.init(root = r"C:\Users\Tim\TOSDataBridge-master/bin")

tosdb.connected()
tosdb.connection_state()== tosdb.CONN_ENGINE_TOS

tosdb.get_block_limit()
tosdb.set_block_limit(20)
tosdb.get_block_limit()

dir(tosdb.TOPICS)

tosdb.TOPICS.ASK.val

print(tosdb.TOSDB_DataBlock.__doc__)


block1 = tosdb.TOSDB_DataBlock(100000, True)

block1.add_items('SPY','QQQ')
block1.add_topics(tosdb.TOPICS.LAST.val, 'bid', 'ask', 'volume')

block1.topics()

block1.topics_precached()

block1.info()
print(block1)

print(tosdb.TOSDB_DataBlock.total_frame.__doc__)

total_frame1 = block1.total_frame(date_time=True, labels=True)
total_frame1.keys()
total_frame1['SPY'].LAST
total_frame1['QQQ'].VOLUME

print(tosdb.TOSDB_DataBlock.topic_frame.__doc__)

topic_frame1=block1.topic_frame("SPY", date_time=False, labels=True)

print(tosdb.TOSDB_DataBlock.item_frame.__doc__)
item_frame1 = block1.item_frame("LAST", date_time=False, labels=True)


print(tosdb.TOSDB_DataBlock.get.__doc__)

block1.get_block_size()
block1.stream_occupancy("SPY","LAST")
block1.get("SPY","Volume", date_time=True, indx=0)
block1.get("SPY","Volume", date_time=True, indx=-1,check_indx=False)

print(tosdb.TOSDB_DataBlock.stream_snapshot.__doc__)
snapshot1= block1.stream_snapshot("SPY", "Last", date_time=False, end=9,beg=0)
snapshot_all= block1.stream_snapshot("SPY","Last", True)
len(snapshot_all)
snapshot_all[0]
snapshot_all[-1]
snapshot_all[0][1] - snapshot_all[-1][1]
snapshot_bad = block1.stream_snapshot("SPY", "Last", True, -1, -1000, smart_size=False)
len(snapshot_bad)
snapshot_bad[0]
snapshot_bad[-1]
block1.stream_occupancy("QQQ","LAST")

print(tosdb.TOSDB_DataBlock.stream_snapshot_from_marker.__doc__)
blssfm = block1.stream_snapshot_from_marker

for _ in range(1):
    get1 = block1.get("SPY", "Last", date_time=True, indx=0)
    time.sleep(3)
    snapshot1= blssfm("SPY", "Last", date_time=True, beg=0)
    time.sleep(8)
    snapshot2 = blssfm("SPY","Last", date_time=True, beg=0)
    snapshot1.reverse()
    snapshot2.reverse()
    for d in [get1] + snapshot1 + snapshot2:
        print(d)

block1.items_precached()

tosdb.clean_up() 

Thanks for the trouble.

**Comment by jeog** [comment]
I've updated your script to wait after adding items/topics to the block (what I discussed in [my last comment](6#issuecomment-340471364)) - see the comments in the code.
```

import tosdb
import time

tosdb.init(root = r"C:\Users\Tim\TOSDataBridge-master/bin")

tosdb.connected()
tosdb.connection_state()== tosdb.CONN_ENGINE_TOS

tosdb.get_block_limit()
tosdb.set_block_limit(20)
tosdb.get_block_limit()

dir(tosdb.TOPICS)

tosdb.TOPICS.ASK.val

print(tosdb.TOSDB_DataBlock.__doc__)

block1 = tosdb.TOSDB_DataBlock(100000, True)

block1.add_items('SPY','QQQ')
block1.add_topics(tosdb.TOPICS.LAST.val, 'bid', 'ask', 'volume')

###
### NOTICE WE ARE SLEEPING TO ALLOW DATA TO GET INTO BLOCK ###
###
print("sleeping for 1.5 seconds")
time.sleep(1.5)
###
### NOTICE WE ARE SLEEPING ###
###

print(block1.topics())
print(block1.topics_precached())
print(block1.info())

print(block1)

print(tosdb.TOSDB_DataBlock.total_frame.__doc__)

total_frame1 = block1.total_frame(date_time=True, labels=True)
print(total_frame1.keys())
print(total_frame1['SPY'].LAST)
print(total_frame1['QQQ'].VOLUME)

print(tosdb.TOSDB_DataBlock.topic_frame.__doc__)
topic_frame1=block1.topic_frame("SPY", date_time=False, labels=True)
print(topic_frame1)

print(tosdb.TOSDB_DataBlock.item_frame.__doc__)
item_frame1 = block1.item_frame("LAST", date_time=False, labels=True)
print(item_frame1)

print(tosdb.TOSDB_DataBlock.get.__doc__)
print(block1.get_block_size())
print(block1.stream_occupancy("SPY","LAST"))
print(block1.get("SPY","Volume", date_time=True, indx=0))
print(block1.get("SPY","Volume", date_time=True, indx=-1,check_indx=False))

print(tosdb.TOSDB_DataBlock.stream_snapshot.__doc__)
snapshot1= block1.stream_snapshot("SPY", "Last", date_time=False, end=9,beg=0)
print(snapshot1)
snapshot_all= block1.stream_snapshot("SPY","Last", True)
print(snapshot_all)
print(len(snapshot_all))
print(snapshot_all[0])
print(snapshot_all[-1])
print(snapshot_all[0][1] - snapshot_all[-1][1])
snapshot_bad = block1.stream_snapshot("SPY", "Last", True, -1, -1000, smart_size=False)
print(len(snapshot_bad))
print(snapshot_bad[0])
print(snapshot_bad[-1])
print(block1.stream_occupancy("QQQ","LAST"))

print(tosdb.TOSDB_DataBlock.stream_snapshot_from_marker.__doc__)
blssfm = block1.stream_snapshot_from_marker

for _ in range(1):
    get1 = block1.get("SPY", "Last", date_time=True, indx=0)
    time.sleep(3)
    snapshot1= blssfm("SPY", "Last", date_time=True, beg=0)
    time.sleep(8)
    snapshot2 = blssfm("SPY","Last", date_time=True, beg=0)
    snapshot1.reverse()
    snapshot2.reverse()
    for d in [get1] + snapshot1 + snapshot2:
        print(d)

print(block1.items_precached())

tosdb.clean_up()
```

I also added a bunch of print commands so you can see returned data if this is run as a script.

**Comment by Theaxx** [comment]
Hi, I think it still does not extract data from TOS. In this section of the code, got this error 

for _ in range(1):
    get1 = block1.get("SPY", "Last", date_time=True, indx=0)
    time.sleep(3)
    snapshot1= blssfm("SPY", "Last", date_time=True, beg=0)
    time.sleep(8)
    snapshot2 = blssfm("SPY","Last", date_time=True, beg=0)
    snapshot1.reverse()
    snapshot2.reverse()
    for d in [get1] + snapshot1 + snapshot2:
        print(d)

AttributeError: 'NoneType' object has no attribute 'reverse'

Not sure what am i not getting right here...

**Comment by jeog** [comment]
Either snapshot1 or 2 is returning 'None' because the 'stream_snapshot_from_marker' call had nothing to return. (I should check for None in my code.) 

This can happen if you run this after the market closes and there's little to no data to return.  If so, try during normal market hours; if you still have a problem paste all the printed output after running it.
