### ISSUE TITLE
How do I get results/outputs from TOS studies/strategies?

### ISSUE THREAD

**Issue by xxwikkixx** [jeog/TOSDataBridge#7]
Hey, I managed to setup your library following the tutorial and it connects successfully to my TOS. I am using python to follow the tutorials and figure out how the library works from your screen shots. I was wondering how can I get the service to get alerts/results/outputs from my studies/strategies running on TOS on a a specific ticker?

**Comment by jeog** [comment]
TOS has 19 custom 'quote' fields whose output you can export like any other topic(LAST, VOLUME etc.). They are not the same thing as traditional studies/strategies but you may be able to wrap a study/strategy in a custom 'quote' field in order to export it.

1) define the custom quote: go to a watchlist or MarketWatch->Quotes and right click on the column header, click customize, select Custom Quotes from the drop-down menu, click on the icon to the left of the name of one of the custom quotes.

2) from there you can use the condition wizard or the thinkscript editor to build the quote. Save when done. (You can change the name but tosdb needs to know the original name: CUSTOM 1, CUSTOM 9 etc.)

3) Once you've saved the custom quote check that it works in TOS first, then add it to your TOSDB_DataBlock using the appropriate topic name, e.g, tosdb.TOPICS.CUSTOM1 or 'CUSTOM1'

I haven't had much time to test this. One time I noticed the appropriate data never showed up in the block, it just kept inserting 'loading' to the stream. It may have been an error in the study or maybe the market was closed so it wasn't calculating or an issue w/ how custom quotes are exported by TOS.

Let me know how it goes.

**Comment by xxwikkixx** [comment]
Hey, thanks for the reply! I tried following this but it didn't work with my study. I am not sure because my study doesn't return quotes. If you want to test in the future let me know i'll give you my study/strategies to see if you could make it work. I am a bit limited on my thinkscript skills. 

However not to give up hope I decided to try a different route using Open CV to detect the signals on my chart visually instead. it seems to be working at the moment and returning the text I see on my chart, which I will forward using some SMS API (twillio maybe) to my phone.

**Comment by jeog** [comment]
It would depend on the nature of the study. Most studies could probably be converted to output some indication of state. A strategy could probably be converted to a boolean output to indicate a signal/trigger. Then tosdb could retrieve that state data. When I get a chance I'll try it out and add some docs or a quick tutorial if I can get it to work.

As to detecting signals, I think you can have TOS email or text when an alert fires: Setup -> ApplicationSettings -> Notifications

**Comment by xxwikkixx** [comment]
I read somewhere TOS alerts dont work with recursive studies, but normal price alert marks work and TOS will send SMS alerts which I do have enabled. 

I'll try to convert my signals to Boolean and then test your library with it.

**Comment by jeog** [comment]
Apparently you need to have the custom quote active in at least one spot on the platform (e.g in a watchlist) WITH EACH SYMBOL you want it to export. (If not you'll just keep getting 'loading' exported.)

So as an example I added the follow to CUSTOM 1 and changed to the interval at the top of the editor to 1m for a 10-minute moving average cross:

    plot data;
    if close crosses above SimpleMovingAvg(10) {
        data = 1;
    } else {
        data = 0;
    }

Then I created a new watchlist; added the 'CUSTOM 1' column to the watchlist; added the symbols I wanted to the watchlist; finally adding those symbols and 'CUSTOM1' topic to the TOSDB_DataBlock which correctly returned 0's.

**Comment by xxwikkixx** [comment]
Hey,

So I got around to setting up the custom quote, and was trying to use your plot data in my study under certain condition. I was hoping you can help me out with this. 

`script VolatilityTrailingStop {
input mult = 2.7; #Multiple of Average True Range to use
input length = 10; #Average True Range period

input Style={default Close, HighLow};
def type;
switch(Style){
case Close:
type=1;
case HighLow:
type=0;
}

def uu=if type then close else high;
def ll=if type then close else low;
def na=double.nan;

def atr = expaverage(high-low,length);

def svs =low+ceil(mult*atr/ticksize())*ticksize();
def lvs =high-ceil(mult*atr/ticksize())*ticksize();

rec shortvs=if isnan(shortvs[1]) then svs else if uu>shortvs[1] then svs else min(svs,shortvs[1]);
rec longvs=if isnan(longvs[1]) then lvs else if ll<longvs[1] then lvs else max(lvs,longvs[1]);

def longswitch=if uu>=shortvs[1] and uu[1]<shortvs[1] then 1 else 0;
def shortswitch=if ll<=longvs[1] and ll[1]>longvs[1] then 1 else 0;

rec direction= compoundvalue(1,if isnan(direction[1]) then 0 else
if direction[1]<=0 and longswitch then 1
else if direction[1]>=0 and shortswitch then -1
else direction[1],0);

plot short=if direction>0 then na else shortvs;
plot long=if direction<0 then na else longvs;

long.SetDefaultColor(color.dark_green);
long.SetStyle(curve.points);
long.SetLineWeight(5);
short.SetDefaultColor(color.dark_red);
short.SetStyle(curve.points);
short.SetLineWeight(5);

def alerttrigger= if direction[1]<=0 and longswitch then 1
else if direction[1]>=0 and shortswitch then 1 else 0;
input alerttext="Alert Text";

input UseAlerts = {false, default true};
input AlertType = {default "BAR", "ONCE", "TICK"};
def at=AlertType;
input AlertSound = {"Bell", "Chimes", default "Ding", "NoSound", "Ring"};
alert(alerttrigger AND UseAlerts, alerttext, if at==1 then Alert.ONCE else if at==2 then Alert.TICK else Alert.BAR, AlertSound);

AssignPriceColor(if long then Color.GREEN else Color.RED);
AssignPriceColor(if short then Color.RED else Color.GREEN);

}

plot data;
if VolatilityTrailingStop().{
    data=1;
}else{
    data=0;
}`

If the assign price color is green I want the data to have a value of 1, and if its red then it should be 0.

**Comment by jeog** [comment]
There might be a better way to do this but let's see if this works first:

In your custom quote editor make a simplified version. (Don't edit the actual indicator, just the one that was copied to the custom quote.) You can also get rid of the 'script' block. I'm not sure if your logic allows for a direction of 0 but I return three states to be sure( 1:long, -1:short, 0:other). 
  
    input mult = 2.7; #Multiple of Average True Range to use
    input length = 10; #Average True Range period

    input Style={default Close, HighLow};
    def type;
    switch(Style){
    case Close:
    type=1;
    case HighLow:
    type=0;
    }

    def uu=if type then close else high;
    def ll=if type then close else low;
    def na=double.nan;

    def atr = expaverage(high-low,length);

    def svs =low+ceil(mult*atr/ticksize())*ticksize();
    def lvs =high-ceil(mult*atr/ticksize())*ticksize();

    rec shortvs=if isnan(shortvs[1]) then svs else if uu>shortvs[1] then svs else min(svs,shortvs[1]);
    rec longvs=if isnan(longvs[1]) then lvs else if ll<longvs[1] then lvs else max(lvs,longvs[1]);

    def longswitch=if uu>=shortvs[1] and uu[1]<shortvs[1] then 1 else 0;
    def shortswitch=if ll<=longvs[1] and ll[1]>longvs[1] then 1 else 0;

    rec direction= compoundvalue(1,if isnan(direction[1]) then 0 else
    if direction[1]<=0 and longswitch then 1
    else if direction[1]>=0 and shortswitch then -1
    else direction[1],0);

    plot data = direction;

**Comment by Dookas** [comment]
@xxwikkixx I noticed earlier in this thread that you were using Open CV in order to send signals to your strategy.  I have a strategy that I cannot seem to work out using the Custom Quote because of the time frames.  I am interested to know how you were using Open CV as I am not very familiar with it.  Thanks!
