### ISSUE TITLE
Tick Strategy

### ISSUE THREAD

**Issue by Dookas** [jeog/TOSDataBridge#8]
I was able to get a signal from a strategy using the custom quote, however I have a strategy that is on a 50 tick chart that I would like to send a signal from.  It seems custom quote only allows minute strategies.  Is there a workaround to send a signal from a tick chart to a python program?

**Comment by jeog** [comment]
I don't see anything in the thinkScript editor that allows for this directly. [Chapter 11 of their manul](http://tlc.thinkorswim.com/center/howToTos/tutorials/Advanced/Chapter-11---Referencing-Secondary-Aggregation.html) mentions other aggregation types but doesn't show any way to use them.

The only other thing I can think of (and I'm no expert on thinkScript) is the 'tick_count' function, which would allow you got get the bar number `def nbar = Floor(tick_count / 50) `; check for a new bar `if nbar > nbar[1] `; and adjust the strategy accordingly.
